[package]
name = "kagc_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
lazy_static = "1.4.0"

kagc_errors = { path = "../kagc_errors" }
kagc_types = { path = "../kagc_types" }
kagc_token = { path = "../kagc_token" }